"""
test_mobile.py — Keyfactor Lab: Mobile Device Certificate Tests
===============================================================
Uses Playwright to simulate real mobile browsers (iPhone and Android)
and verify that a locally served certificate is trusted and readable.

This test spins up a local HTTPS server using the generated certificate,
then opens it in an emulated mobile browser and checks for SSL errors.

Run with: pytest test_mobile.py -v
Requires: pip install pytest playwright pytest-playwright
          playwright install chromium
          
          
          
Update thsi to allow the chnage
"""

# subprocess runs terminal commands from Python — used for OpenSSL and server
import subprocess

# os gives us file system access for creating and deleting files
import os

# threading lets us run the local HTTPS server in the background
# while Playwright tests run in the foreground
import threading

# ssl and http.server let us spin up a local HTTPS server using our certificate
import ssl
import http.server

# time gives us sleep() to wait for the server to start before testing
import time

# pytest is the testing framework
import pytest

# playwright provides browser automation — sync_playwright runs it synchronously
from playwright.sync_api import sync_playwright, expect

# x509 lets us inspect the certificate fields in the mobile trust tests
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from datetime import datetime, timezone


# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

# Certificate files — generated by the setup fixture below
CERT_FILE = "my_cert.pem"
KEY_FILE  = "my_key.pem"
CONFIG_FILE = "openssl_mobile.cnf"

# Local HTTPS server settings
# The test server runs on this port during the test session
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 8443
SERVER_URL  = f"https://{SERVER_HOST}:{SERVER_PORT}"

# Validity settings
CERT_VALIDITY_DAYS  = 365
EXPIRY_WARNING_DAYS = 30
MIN_KEY_SIZE        = 2048
EXPECTED_ISSUER     = "KeyfactorLab-RootCA"

# OpenSSL config — same approach as test_certs.py for cross-platform reliability
OPENSSL_CONFIG = """
[req]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_ca

[dn]
CN = KeyfactorLab-RootCA
O  = KeyfactorLab
C  = US

[v3_ca]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:true
keyUsage               = critical, digitalSignature, cRLSign, keyCertSign
"""

# Mobile device profiles to emulate
# These match real device specs used by Playwright's device registry
# Each device gets its own browser context with the correct screen size,
# user agent, and touch/pixel settings
MOBILE_DEVICES = [
    {
        "name": "iPhone 14",
        "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15",
        "viewport": {"width": 390, "height": 844},
        "device_scale_factor": 3,
        "is_mobile": True,
        "has_touch": True,
    },
    {
        "name": "Samsung Galaxy S23 (Android)",
        "user_agent": "Mozilla/5.0 (Linux; Android 13; SM-S911B) AppleWebKit/537.36",
        "viewport": {"width": 360, "height": 780},
        "device_scale_factor": 3,
        "is_mobile": True,
        "has_touch": True,
    },
    {
        "name": "iPad Pro",
        "user_agent": "Mozilla/5.0 (iPad; CPU OS 16_0 like Mac OS X) AppleWebKit/605.1.15",
        "viewport": {"width": 1024, "height": 1366},
        "device_scale_factor": 2,
        "is_mobile": True,
        "has_touch": True,
    },
]


# ─────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────

def generate_cert():
    """
    Generates a self-signed certificate using an OpenSSL config file.
    Same approach as test_certs.py — config file avoids Windows -subj issues.
    """
    print(f"\n{'='*55}")
    print("  Keyfactor Lab — Mobile Certificate Tests")
    print(f"{'='*55}")
    print(f"  Generating certificate...")

    # Write the OpenSSL config file
    with open(CONFIG_FILE, "w") as f:
        f.write(OPENSSL_CONFIG)

    command = [
        "openssl", "req",
        "-x509",
        "-newkey", "rsa:2048",
        "-keyout", KEY_FILE,
        "-out", CERT_FILE,
        "-days", str(CERT_VALIDITY_DAYS),
        "-nodes",
        "-config", CONFIG_FILE
    ]

    result = subprocess.run(command, capture_output=True, text=True)

    # Clean up config file immediately after use
    if os.path.exists(CONFIG_FILE):
        os.remove(CONFIG_FILE)

    if result.returncode != 0:
        raise RuntimeError(f"OpenSSL failed:\n{result.stderr}")

    print("  Certificate  : created ✓")
    print("  Private key  : created ✓")


def start_https_server():
    """
    Starts a local HTTPS server in a background thread using our certificate.
    This gives Playwright a real HTTPS endpoint to connect to during tests.
    The server runs on SERVER_PORT and serves a simple HTML page.
    """

    # A minimal HTTP handler that serves a simple HTML response
    # Playwright will load this page and check for SSL/cert errors
    class CertTestHandler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            # Send a 200 OK response with a simple HTML body
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            self.wfile.write(b"""
                <html>
                  <head><title>Keyfactor Lab — Cert Test</title></head>
                  <body>
                    <h1>Certificate Test Server</h1>
                    <p>If you can read this, the certificate was accepted.</p>
                    <p id='status'>CERT_OK</p>
                  </body>
                </html>
            """)

        # Silence the default request logging so test output stays clean
        def log_message(self, format, *args):
            pass

    # Create the HTTPS server and wrap it with our SSL certificate
    httpd = http.server.HTTPServer((SERVER_HOST, SERVER_PORT), CertTestHandler)

    # Create an SSL context and load our cert and key
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)
    httpd.socket = ssl_context.wrap_socket(httpd.socket, server_side=True)

    # Run the server in a background daemon thread
    # daemon=True means the thread dies automatically when the main process exits
    server_thread = threading.Thread(target=httpd.serve_forever)
    server_thread.daemon = True
    server_thread.start()

    # Give the server a moment to fully start before tests begin
    time.sleep(1)
    print(f"  HTTPS server : running at {SERVER_URL} ✓")
    return httpd


def load_cert(path):
    """
    Opens a .pem certificate file and returns a parsed certificate object.
    """
    with open(path, "rb") as f:
        return x509.load_pem_x509_certificate(f.read(), default_backend())


def cleanup():
    """Deletes generated certificate and key files."""
    for filename in [CERT_FILE, KEY_FILE]:
        if os.path.exists(filename):
            os.remove(filename)
            print(f"  Deleted: {filename}")


# ─────────────────────────────────────────────
# PYTEST FIXTURES
# ─────────────────────────────────────────────

@pytest.fixture(scope="session", autouse=True)
def setup_environment():
    """
    Session-scoped fixture that:
    BEFORE tests: generates the cert and starts the HTTPS server
    AFTER tests:  shuts down the server and deletes cert files
    """
    # Generate the certificate
    generate_cert()

    # Start the local HTTPS test server
    server = start_https_server()

    print(f"{'='*55}\n")

    # Hand control to the tests
    yield

    # Teardown — shut down server and clean up files
    print(f"\n{'='*55}")
    print("  Shutting down test server...")
    server.shutdown()
    print("  Cleaning up files...")
    cleanup()
    print(f"{'='*55}\n")


# ─────────────────────────────────────────────
# CERTIFICATE FIELD TESTS (same as test_certs.py)
# These run on all platforms including mobile pipeline
# ─────────────────────────────────────────────

def test_cert_not_expired():
    """TEST 1: Certificate has not expired."""
    cert = load_cert(CERT_FILE)
    assert cert.not_valid_after_utc > datetime.now(timezone.utc), \
        "FAIL: Certificate is expired!"


def test_cert_key_size():
    """TEST 2: Certificate key is at least 2048 bits."""
    cert = load_cert(CERT_FILE)
    key_size = cert.public_key().key_size
    assert key_size >= MIN_KEY_SIZE, \
        f"FAIL: Key size {key_size} bits is below minimum {MIN_KEY_SIZE}"


def test_cert_expiry_warning():
    """TEST 3: Certificate has more than 30 days remaining."""
    cert = load_cert(CERT_FILE)
    days_remaining = (cert.not_valid_after_utc - datetime.now(timezone.utc)).days
    assert days_remaining > EXPIRY_WARNING_DAYS, \
        f"FAIL: Cert expiring in {days_remaining} days!"


# ─────────────────────────────────────────────
# MOBILE BROWSER TESTS
# These use Playwright to simulate real mobile devices
# ─────────────────────────────────────────────

@pytest.mark.parametrize("device", MOBILE_DEVICES, ids=[d["name"] for d in MOBILE_DEVICES])
def test_mobile_page_loads(device):
    """
    TEST 4: Verify the certificate-secured page loads on each mobile device.

    Opens the local HTTPS server in a Chromium browser configured to emulate
    a real mobile device (iPhone, Android, iPad). Checks that the page loads
    without errors and the expected content is present.

    ignore_https_errors=True is used here because our cert is self-signed
    and not trusted by the OS. In a real environment with a CA-issued cert,
    this would be False — the cert would be trusted natively.
    This mirrors how Keyfactor's product eliminates the need for self-signed
    certs by providing properly trusted enterprise certificates.

    @pytest.mark.parametrize runs this test once for each device in MOBILE_DEVICES
    """
    with sync_playwright() as p:
        # Launch a headless Chromium browser (no visible window)
        # headless=True is required for CI/CD pipelines
        browser = p.chromium.launch(headless=True)

        # Create a browser context configured to emulate this specific mobile device
        # This sets screen size, user agent, touch support, and pixel density
        context = browser.new_context(
            user_agent=device["user_agent"],
            viewport=device["viewport"],
            device_scale_factor=device["device_scale_factor"],
            is_mobile=device["is_mobile"],
            has_touch=device["has_touch"],
            ignore_https_errors=True,   # required for self-signed certs
        )

        # Open a new browser tab
        page = context.new_page()

        # Navigate to our local HTTPS server
        response = page.goto(SERVER_URL, timeout=10000)

        # Verify the server returned a successful HTTP status code (200 = OK)
        assert response.status == 200, \
            f"FAIL: {device['name']} got HTTP {response.status} — expected 200"

        # Verify the page content contains our expected marker text
        # This confirms the full page loaded, not just the HTTP headers
        content = page.content()
        assert "CERT_OK" in content, \
            f"FAIL: {device['name']} — expected content not found in page"

        print(f"  {device['name']}: page loaded ✓")

        # Close the browser context and browser to free memory
        context.close()
        browser.close()


@pytest.mark.parametrize("device", MOBILE_DEVICES, ids=[d["name"] for d in MOBILE_DEVICES])
def test_mobile_user_agent(device):
    """
    TEST 5: Verify each device is presenting the correct mobile user agent.

    This confirms the browser context is properly configured as a mobile device.
    In enterprise PKI testing, user agent verification matters because some
    certificate policies are enforced differently based on client type.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)

        # Create context with the device's user agent
        context = browser.new_context(
            user_agent=device["user_agent"],
            viewport=device["viewport"],
            is_mobile=device["is_mobile"],
            ignore_https_errors=True,
        )

        page = context.new_page()
        page.goto(SERVER_URL, timeout=10000)

        # Use JavaScript to read the browser's actual user agent string
        # This confirms Playwright correctly applied the mobile device profile
        actual_ua = page.evaluate("() => navigator.userAgent")

        # Verify the user agent contains expected mobile keywords
        assert device["user_agent"].split()[0] in actual_ua, \
            f"FAIL: {device['name']} user agent mismatch"

        print(f"  {device['name']}: user agent verified ✓")

        context.close()
        browser.close()